### ISSUE TITLE
Cannot find /Classes/CDVViewController.h (iOS)

### ISSUE THREAD

**Issue by felipecocco** [adnathan/ace#17]
It appears the correct path is Classes/Public/CDVViewController.h

However, even after making this switch, project fails to initialize (using Ionic + Cordova native 4.0.1)

**Comment by adnathan** [comment]
The compilation error should now be fixed.  Can you share what initialization error you get?  Thanks!

**Comment by felipecocco** [comment]
I don't know if I'm getting the updated plugin or not, because I just added the plugin back in but I still get the compilation error.

And when it comes to initialization, the Ionic app just doesn't boot -- I keep getting the spinning icon in the splash screen but the app never initializes (this is just the default ionic app that I got from ionic start)

To reproduce

ionic start myProject
cd myProject
ionic plugin add cordova-plugin-ace
ionic emulate
--- Build Fails  -- 
Fix path to CDVViewController.h
ionic emulate
Emulator runs but app never starts

**Comment by adnathan** [comment]
Oh, I'll update the plugin on NPM later tonight. That's where it's coming from when you add it as "cordova-plugin-ace." I'll also try your exact steps to see what I get.

On Mar 9, 2016, at 5:22 PM, felipecocco <notifications@github.com<mailto:notifications@github.com>> wrote:

I don't know if I'm getting the updated plugin or not, because I just added the plugin back in but I still get the compilation error.

And when it comes to initialization, the Ionic app just doesn't boot -- I keep getting the spinning icon in the splash screen but the app never initializes (this is just the default ionic app that I got from ionic start)

To reproduce

ionic start myProject
cd myProject
ionic plugin add cordova-plugin-ace
ionic emulate
--- Build Fails --
Fix path to CDVViewController.h
ionic emulate
Emulator runs but app never starts

##

**Comment by wellsayd** [comment]
I am seeing the same issue as felipecocco

**Comment by adnathan** [comment]
I've published a new version to NPM with all the latest fixes. Please let me know if you still see this after reinstalling the plugin (version 0.0.15). Thank you!

**Comment by felipecocco** [comment]
Fires up great now on Ionic!
